language: R
sudo: false
cache: packages
warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  mkdir ~/.R && echo "CXX=g++-4.9" > ~/.R/Makevars
